version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "31000:8080"
    environment:
      - TZ=${TZ}
      - OLLAMA_API_BASE_URL=http://${OLLAMA_HOST}:11434/api
    volumes:
      - ${DOCKER_DIR}/openwebui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:${OLLAMA_HOST}"
