version: '3.8'

services:
  ansible:
    image: cytopia/ansible:latest
    container_name: ansible
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKER_DIR}/ansible:/ansible
      - ${DOCKER_DIR}/ansible/ssh:/root/.ssh:ro
    working_dir: /ansible
    environment:
      - TZ=${TZ}
      - ANSIBLE_HOST_KEY_CHECKING=False
    tty: true
    stdin_open: true
